version: "3.9"
services:
  db:
    container_name: database_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
    expose:
      - 5432
    networks:
      - internal
    labels:
      - traefik.enable=false
    ports:
      - "${DB_PORT}:5432"
  backend:
    container_name: fastapi_container
    build:
      context: ./backend
      dockerfile: prod.DockerFile
    command: bash -c "poetry run alembic upgrade head && poetry run main"
    env_file:
      - .env
    expose:
      - 8000
    networks:
      - web
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`api.${DOMAIN}`)"
    depends_on:
      - db
      - traefik
  frontend:
    container_name: angular_container
    build:
      context: ./frontend
      dockerfile: prod.DockerFile
    expose:
       - 4200
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.rule=Host(`${DOMAIN}`)"
    networks:
      - web
    depends_on:
      - backend
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN}`)"
    networks:
      - internal
      - web
    depends_on:
      - db
      - traefik
  traefik:
    image: traefik
    container_name: traefik_container
    domainname: ${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=user-auth@file"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./traefik-data/traefik.yml:/traefik.yml:ro
        - ./:/etc/traefik
        - ./traefik-data/acme.json:/acme.json
        - ./traefik-data/configurations:/configurations
    networks:
      - web


networks:
  web:
    external: true
  internal:
    external: false