version: "3.9"
services:
  db:
    container_name: database_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
    expose:
      - 5432
    ports:
      - "${DB_PORT}:5432"
  backend:
    container_name: fastapi_container
    build:
      context: ./backend
      dockerfile: prod.DockerFile
    command: bash -c "poetry run alembic upgrade head && poetry run main"
    env_file:
      - .env
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=((Host(`${DOMAIN}`) && PathPrefix(`/api`)) || Host(`swagger.${DOMAIN}`))"
    depends_on:   
      - db
      - traefik
      - mongodb
  frontend:
    container_name: angular_container
    build:
      context: ./frontend
      dockerfile: prod.DockerFile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.angular.rule=Host(`${DOMAIN}`)"
    depends_on:
      - backend
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`comments.${DOMAIN}`)"
    depends_on:
      - db
      - traefik
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - "${MONGO_PORT}:27017"
  traefik:
    image: traefik
    container_name: traefik_container
    ports:
      - "80:80"
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
