"""tags

Revision ID: 6dec9fcf749e
Revises: a2d51007cc46
Create Date: 2022-06-11 13:25:08.282569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dec9fcf749e'
down_revision = 'a2d51007cc46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('vote', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'tags')
    op.drop_column('applications', 'tags')
    # ### end Alembic commands ###
